#spring:
#  application:
#    name: zuul
#  cloud:
#    config:
#      override-none: true
#
#server:
#  port: 3001
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#
#zuul:
#  retryable: true
#  sensitive-headers:
#
#    #  routes:
#    #    item-service: /item-service/**
#    #    user-service: /user-service/**
#    #    order-service: /order-service/**
#
#ribbon:
#  ConnectTimeout: 1000
#  ReadTimeout: 1000
#  MaxAutoRetriesNextServer: 1
#  MaxAutoRetries: 1
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 500
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
spring:
  sleuth:
    sampler:
      probability: 0.1

eureka:
  instance:
    prefer-ip-address: true # 使用ip进行注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 界面列表中显示的格式也显示ip
