
#spring:
#  application:
#    name: item-service
#
#server:
#  port: 8001
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
spring:
  sleuth:
    sampler:
      probability: 0.1

eureka:
  instance:
    prefer-ip-address: true # 使用ip进行注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 界面列表中显示的格式也显示ip